#!/usr/bin/env bash
# gate.sh <label> <sha> — the per-commit gate on a committed tree (gate-at).
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

usage() {
	cat <<EOF
usage: gate.sh <label> <sha>

Runs the per-commit gate — make lint, make test, make test-race, make build,
make test-cli — on the COMMITTED tree at <sha>, exported to a scratch
directory (the working tree may hold edits). Stops at the first failing step,
like &&, and prints GATE_STEP <name> rc=<rc> elapsed=<s> for each step run.

Concurrent gates share golangci-lint's lock. Both lint passes (plain and
GOOS=darwin) go through a generated wrapper, \$OUT/lintwrap/golangci-lint,
that adds --allow-serial-runners to 'run', so a second gate waits for the
lock instead of failing. The Makefile re-prepends the mise shims to PATH, so
the wrapper is put first with a command-line PATH:
  make lint PATH="\$OUT/lintwrap:\$HOME/.local/share/mise/shims:\$PATH"
GATE_LINTWRAP runs=<n> darwin=<n> shows how many lint passes used it.

Log: \$OUT/gate-<stamp>.log (every step's output, in order).
$CV_HELP_COMMON
EOF
}

if cv_wants_help "$@"; then usage; exit 0; fi
cv_setup GATE
[[ $# -eq 2 ]] || { usage >&2; die 2 "want <label> <sha>"; }
cv_label "$1"
cv_resolve "$2"
stamp=$(cv_stamp)
CV_LOG=$OUT/gate-$stamp.log
: >"$CV_LOG"

# The lint wrapper. The real golangci-lint is whatever this PATH finds (the
# mise shim, which picks the version from the export's .mise.toml).
real=$(command -v golangci-lint) || die 2 "golangci-lint not found on PATH"
wrapdir=$OUT/lintwrap
mkdir -p "$wrapdir" || die 2 "cannot create $wrapdir"
tmpw=$(mktemp "$wrapdir/.golangci-lint.XXXX") || die 2 "cannot write the lint wrapper"
cat >"$tmpw" <<EOF
#!/usr/bin/env bash
# Generated by scripts/verify/gate.sh. Concurrent gates share golangci-lint's
# lock: 'run' waits for it (--allow-serial-runners) instead of failing.
if [[ -n \${CV_LINTWRAP_LOG:-} ]]; then printf '%s GOOS=%s %s\n' "\$(date +%T)" "\${GOOS:-}" "\$*" >>"\$CV_LINTWRAP_LOG"; fi
real=$(printf '%q' "$real")
if [[ \${1:-} == run ]]; then shift; exec "\$real" run --allow-serial-runners "\$@"; fi
exec "\$real" "\$@"
EOF
chmod 755 "$tmpw" && mv -f "$tmpw" "$wrapdir/golangci-lint" || die 2 "cannot install the lint wrapper"
export CV_LINTWRAP_LOG=$OUT/gate-$stamp.lintwrap
: >"$CV_LINTWRAP_LOG"

export_tree "$CV_SHA_FULL"
tree=$CV_LAST_EXPORT
echo "gate at $CV_SHA_FULL in $tree" >>"$CV_LOG"

step_lint() { cd "$tree" && make lint PATH="$wrapdir:$HOME/.local/share/mise/shims:$PATH"; }
step_test() { cd "$tree" && make test; }
step_test_race() { cd "$tree" && make test-race; }
step_build() { cd "$tree" && make build; }
step_test_cli() { cd "$tree" && make test-cli; }

rc=0
for step in lint test test-race build test-cli; do
	offset=$(($(wc -c <"$CV_LOG") + 1))
	echo "=== GATE_STEP $step start $(date +%T)" >>"$CV_LOG"
	s0=$(date +%s)
	cv_run "$CV_LOG" "step_${step//-/_}"
	src=$?
	line="GATE_STEP $step rc=$src elapsed=$(($(date +%s) - s0))"
	echo "$line"
	if [[ $step == lint ]]; then
		runs=$(grep -c ' run' "$CV_LINTWRAP_LOG")
		darwin=$(grep -c 'GOOS=darwin .*run' "$CV_LINTWRAP_LOG")
		echo "GATE_LINTWRAP runs=$runs darwin=$darwin" | tee -a "$CV_LOG"
		if ((src == 0 && (runs < 2 || darwin < 1))); then
			echo "gate.sh: make lint passed but did not run both passes through $wrapdir/golangci-lint" >&2
			rc=2
			break
		fi
	fi
	if ((src != 0)); then
		rc=1
		hits=$(tail -c +"$offset" "$CV_LOG" | grep -E '^(--- FAIL|FAIL|panic:)|^[^ ]+\.go:[0-9]+:[0-9]+: ' | head -20)
		if [[ -n $hits ]]; then echo "$hits"; else tail -c +"$offset" "$CV_LOG" | tail -20; fi
		echo "$line" >>"$CV_LOG"
		break
	fi
	echo "$line" >>"$CV_LOG"
done
exit "$rc"
